version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - '8097:8097'
    volumes:
      - ./Backend:/usr/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongo

  frontend:
    build:
      context: ./my-shopping-cart
    ports:
      - '4321:4321'
    volumes:
      - ./my-shopping-cart:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - '8080:8080'
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - '27017:27017'
